CREATE TABLE IB_FILE_OPS_APP.TELEBOT_USER
(
    id              VARCHAR2(36) DEFAULT REGEXP_REPLACE(SYS_GUID(), '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')
        NOT NULL,

    date_created    DATE         DEFAULT SYSDATE                                     NOT NULL,
    date_updated    DATE,
    user_id         NVARCHAR2(36)                                                    NOT NULL,
    user_id_updated NVARCHAR2(36),
    customer_id     NVARCHAR2(36)                                                    NOT NULL,
    file_name       NVARCHAR2(200)                                                   NOT NULL,
    file_extension  NVARCHAR2(20),
    pattern_id      NUMBER,
    hash_sum        VARCHAR2(64)                                                     NOT NULL, -- SHA-256 hash
    -- status code, f.e. CANCELLED
    status_cd       VARCHAR2(20),

    CONSTRAINT file_upload_info_pk PRIMARY KEY (id)
);

CREATE TABLE IB_FILE_OPS_APP.TELEBOT_MESSAGE
(
    file_id      VARCHAR2(36),
    file_content BLOB,

    CONSTRAINT file_upload_content_pk PRIMARY KEY (file_id)
);

CREATE TABLE IB_FILE_OPS_APP.TELEBOT_GROUP
(
    id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    type_cd     NVARCHAR2(50) NOT NULL,
    description NVARCHAR2(1000),

    CONSTRAINT dictionary_type_pk PRIMARY KEY (id)
);

CREATE TABLE IB_FILE_OPS_APP.TELEBOT_LNK_USER_GROUP
(
    id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    type_cd       NVARCHAR2(50) NOT NULL,
    item_cd       NVARCHAR2(50) NOT NULL,
    sorting_order NUMBER,
    description   NVARCHAR2(1000),

    CONSTRAINT dictionary_item_pk PRIMARY KEY (id)
);

grant select, insert, update on IB_FILE_OPS_APP.TELEBOT_USER to CBS, CINT_CALLER, MINT_CALLER;
grant select, insert, update on IB_FILE_OPS_APP.TELEBOT_MESSAGE to CBS, CINT_CALLER, MINT_CALLER;
grant select on IB_FILE_OPS_APP.TELEBOT_GROUP to CBS, CINT_CALLER, MINT_CALLER;
grant select on IB_FILE_OPS_APP.TELEBOT_LNK_USER_GROUP to CBS, CINT_CALLER, MINT_CALLER;